### ISSUE TITLE
customise aspect of steps and content of steps

### ISSUE THREAD

**Issue by Thebigbignooby** [mu29/react-stepper#2]
Say I don't want completed steps to be coloured in full but only have a border coloured.

also Would like to replace numbers inside the steps with custom icons. Is this possible ?

**Comment by claytn** [comment]
I am working on the border properties now. Just waiting until my opacity pull request gets merged. I can look into adding icons aside inside each circle instead of numbers.

**Comment by claytn** [comment]
Update: Pull request for border implementation has been made. Nothing new on the icons though.
