### ISSUE TITLE
Fix react validator warnings

### ISSUE THREAD

**Issue by vmasalov** [mu29/react-stepper#3]
There are bunch of warnings in the web console. Could you fix it? 

`Warning: Failed prop type: Step: prop type `active` is invalid; it must be a function, usually from React.PropTypes.
    in Step (created by Stepper)...`

`Warning: Failed prop type: Step: prop type `completed` is invalid; it must be a function, usually from React.PropTypes.
    in Step (created by Stepper)...`

`Warning: Failed prop type: Step: prop type `first` is invalid; it must be a function, usually from React.PropTypes.
    in Step (created by Stepper)...`

`Warning: Failed prop type: Step: prop type `last` is invalid; it must be a function, usually from React.PropTypes.
    in Step (created by Stepper)...`

`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Stepper`. See https://fb.me/react-warning-keys for more information.
    in Step (created by Stepper)...`

**Comment by mu29** [comment]
#4 May solved it
